// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Category struct {
	ID           int64  `json:"id"`
	CategoryName string `json:"category_name"`
}

type Post struct {
	ID           int64     `json:"id"`
	PostImage    []byte    `json:"post_image"`
	Title        string    `json:"title"`
	PostCategory int64     `json:"post_category"`
	Content      string    `json:"content"`
	TimeForRead  int32     `json:"time_for_read"`
	LikeNumber   int64     `json:"like_number"`
	CreatedAt    time.Time `json:"created_at"`
}

type Review struct {
	ID            int64     `json:"id"`
	Reviewer      string    `json:"reviewer"`
	ReviewContent string    `json:"review_content"`
	Post          int64     `json:"post"`
	StarDegree    float64   `json:"star_degree"`
	LikeNumber    int64     `json:"like_number"`
	UnlikeNumber  int64     `json:"unlike_number"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	UserImage      []byte    `json:"user_image"`
	CreatedAt      time.Time `json:"created_at"`
}
