// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, categoryName string) (Category, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, id int64) error
	DeleteReview(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListGoods(ctx context.Context, arg ListGoodsParams) ([]Review, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
